apiVersion: v1
kind: Namespace
metadata:
  name: conformance

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: conformance
  name: conformance
  namespace: conformance

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: conformance
  name: conformance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conformance
subjects:
- kind: ServiceAccount
  name: conformance
  namespace: conformance

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: conformance
  name: conformance
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '/metrics'
  - '/logs'
  - '/logs/*'
  verbs:
  - 'get'
