name: ci
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Create Kubernetes cluster (kind)
        uses: engineerd/setup-kind@v0.3.0
        id: kind
        with:
          version: v0.7.0

      - name: Install ingress controller
        run: |
          # The secret points to the gist https://gist.github.com/aledbf/7e67bcb338fa6a1696eb5b101597224e
          # easy to fork/change and test a different controller
          curl ${{ secrets.INGRESS_CONTROLLER }} | bash

      - name: Setup environment
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      - name: Set up Go 1.14
        uses: actions/setup-go@master
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go dependencies
        run: |
          go get -u github.com/jteeuwen/go-bindata/...

      - name: Build image
        shell: bash
        run: |
          cd go/src/github.com/${{ github.repository }}
          go mod download
          TAG=dev REGISTRY=kubernetes-sigs make build-image

      # Use go test
      #- name: Run tests
      #  shell: bash
      #  run: |
      #    cd go/src/github.com/${{ github.repository }}
      #    go mod download
      #    make test

      # Use a pod
      - name: Run tests
        shell: bash
        run: |
          kubectl get nodes

          kind load docker-image kubernetes-sigs/ingress-conformance:dev

          kubectl run conformance \
            --attach \
            --restart=Never \
            --generator=run-pod/v1 \
            --image-pull-policy=Never \
            --image=kubernetes-sigs/ingress-conformance:dev
