name: ci
on: [push]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Create Kubernetes cluster (kind)
        uses: engineerd/setup-kind@v0.3.0
        id: kind
        with:
          version: v0.7.0
          config: .github/kind.yaml

      - name: Install ingress controller
        run: |
          # The secret points to the gist https://gist.github.com/aledbf/7e67bcb338fa6a1696eb5b101597224e
          # easy to fork/change and test a different controller.
          curl -sSL ${{ secrets.INGRESS_CONTROLLER }} | bash

      - name: Set up Go 1.14
        uses: actions/setup-go@master
        with:
          go-version: 1.14
        id: go

      - name: Cache for go dependencies
        uses: actions/cache@v1.1.2
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-

      - name: Cache for maven dependencies
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Go dependencies
        run: |
          go get -u github.com/jteeuwen/go-bindata/...

      - name: Go modules
        run: |
          go mod download

      - name: Build container image
        shell: bash
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin

          # use a local image
          export TAG=dev
          export REGISTRY=kubernetes-sigs

          make build-image

      # Use go test
      - name: Run tests (go test)
        shell: bash
        run: |
          # TODO: fix "testing: warning: no tests to run"
          go test --output-file reports/ingress-conformance.json --format cucumber || true

      - uses: actions/upload-artifact@v1
        with:
          name: ingress-conformance.json
          path: reports/ingress-conformance.json

      # Check tests run as a pod
      - name: Run tests (pod)
        shell: bash
        run: |
          echo "Loading test image to kind cluster..."
          kind load docker-image kubernetes-sigs/ingress-conformance:dev

          echo "Creating service account with privileges to create resources..."
          kubectl apply -f images/conformance/conformance.yaml

          echo "Running tests using a pod..."
          kubectl run conformance \
            --attach \
            --restart=Never \
            --generator=run-pod/v1 \
            --image-pull-policy=Never \
            --namespace=conformance \
            --overrides='{ "apiVersion": "v1", "spec":{"serviceAccountName": "conformance"}}' \
            --image=kubernetes-sigs/ingress-conformance:dev


  reports:
    name: Build reports
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up JDK 11 (required for reports)
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/download-artifact@v1
        with:
          name: ingress-conformance.json
          path: reports

      - name: Build report
        shell: bash
        run: |
          export OUTPUT_DIRECTORY=$PWD/reports/output
          export INPUT_JSON=$PWD/reports/ingress-conformance.json
          export TREND_JSON=$PWD/reports/output/trends.json

          cd reports/build
          mvn clean compile exec:java

          cp ../output/cucumber-html-reports/overview-features.html ../output/cucumber-html-reports/index.html

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports/output/cucumber-html-reports

  gh-pages:
    name: Update gh-pages
    runs-on: ubuntu-latest
    needs: reports

    steps:

      - uses: actions/download-artifact@v1
        with:
          name: reports
          path: reports/output/cucumber-html-reports

      - name: Deploy report to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/output/cucumber-html-reports
