name: ci
on: [push]

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Create Kubernetes cluster (kind)
        uses: engineerd/setup-kind@v0.3.0
        id: kind
        with:
          version: v0.7.0

      - name: kubeconfig
        shell: bash
        run: |
          kind get kubeconfig > .kubeconfig

      - name: Upload kubeconfig
        uses: actions/upload-artifact@v1
        with:
          name: kubeconfig
          path: .kubeconfig

      - name: Install ingress controller
        run: |
          kubectl version

          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml
          #echo "Configuring deployment..."
          #kubectl patch deployments -n ingress-nginx nginx-ingress-controller -p '{"spec":{"template":{"spec":{"containers":[{"name":"nginx-ingress-controller","ports":[{"containerPort":80,"hostPort":80},{"containerPort":443,"hostPort":443}]}],"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Setup environment
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      - name: Set up Go 1.14
        uses: actions/setup-go@master
        with:
          go-version: 1.14
        id: go

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go dependencies
        run: |
          go get -u github.com/jteeuwen/go-bindata/...

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}

      - name: Download kubeconfig
        uses: actions/download-artifact@v1
        with:
          name: kubeconfig
          path: go/src/github.com/${{ github.repository }}

      # Use go test
      - name: Run tests
        shell: bash
        run: |
          export KUBECONFIG=go/src/github.com/${{ github.repository }}/.kubeconfig
          cat $KUBECONFIG

          cd go/src/github.com/${{ github.repository }}

          go mod download
          make test

      # Use a pod
      #- name: Run tests
      #  shell: bash
      #  run: |
      #    kubectl run --rm \
      #      --attach \
      #      --restart=Never \
      #      --generator=run-pod/v1 \
      #      kubernetes-sigs/ingress-conformance:dev
